language: python
python:
  - "3.5"

before_install:
  - phantomjs --version # 输出 phantomjs 版本

# command to install dependencies
install:
  - pip install -r req.txt

before_script:
  - ls

script:
  - python3 leetcode_generate.py

after_script:
  - git init
  - git config user.name "bonfy"  #修改name
  - git config user.email "foreverbonfy@163.com"  #修改email
  - git add .
  - git commit -m "update auto by tracis-ci"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

env:
 global:
   - GH_REF: github.com/bonfy/leetcode
