# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Return the letter that was added to t.
#
#  
# Example 1:
#
#
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
#
#
# Example 2:
#
#
# Input: s = "", t = "y"
# Output: "y"
#
#
# Example 3:
#
#
# Input: s = "a", t = "aa"
# Output: "a"
#
#
# Example 4:
#
#
# Input: s = "ae", t = "aea"
# Output: "a"
#
#
#  
# Constraints:
#
#
# 	0 <= s.length <= 1000
# 	t.length == s.length + 1
# 	s and t consist of lower-case English letters.
#
#


#
# @lc app=leetcode id=389 lang=python3
#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference/description/
#
# algorithms
# Easy (53.50%)
# Total Accepted:    155.5K
# Total Submissions: 290.3K
# Testcase Example:  '"abcd"\n"abcde"'
#
# 
# Given two strings s and t which consist of only lowercase letters.
# 
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
# 
# Find the letter that was added in t.
# 
# Example:
# 
# Input:
# s = "abcd"
# t = "abcde"
# 
# Output:
# e
# 
# Explanation:
# 'e' is the letter that was added.
# 
#
class Solution:
    def findTheDifference(self, s, t):
        hash_s = {}
        for i in s:
            hash_s[i] = hash_s.get(i, 0) + 1
        for i in t:
            if i not in hash_s or hash_s[i] == 0:
                return i
            else:
                hash_s[i] -= 1
            
        


